services:
  database_new:  # Nuevo nombre para el servicio de base de datos
    image: postgres:latest
    container_name: database_new  # Nuevo nombre
    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_contraseña
    ports:
      - "5434:5432"
    volumes:
      - database_volume_new:/var/lib/postgresql/data  # Nuevo nombre del volumen

  api_new:  # Nuevo nombre para el backend
    build: ./backend
    container_name: api_new  # Nuevo nombre
    ports:
      - "8082:80"
    depends_on:
      - database_new  # Actualizamos la dependencia

  web_new:  # Nuevo nombre para el frontend
    image: nginx:latest
    container_name: web_new  # Nuevo nombre
    ports:
      - "8083:80"
    depends_on:
      - api_new  # Actualizamos la dependencia

volumes:
  database_volume_new:  # Nuevo nombre del volumen
